extends SceneTree

func _init() -> void:
	call_deferred("run")

func capture(label: String) -> void:
	root.get_node("TinyWorkshop")._refresh_ui()
	await process_frame
	await RenderingServer.frame_post_draw
	root.get_texture().get_image().save_png(OS.get_environment("TEMP") + "/hardware_" + label + ".png")

func run() -> void:
	var state := root.get_node("GameState") as HardwareEmpireState
	state.start_tiny_workshop()
	var scene = load("res://scenes/tiny_workshop.tscn").instantiate()
	root.add_child(scene)
	scene.set_process(false)
	root.size = Vector2i(1440,900)
	scene._update_entities()
	await capture("empty")
	state.advance(8)
	scene._update_entities()
	scene._show_front_desk()
	await capture("front")
	scene._show_job(state.repair_shop.jobs[0].id)
	await capture("request")
	scene._close_panel()
	state.interact_tiny_station("front_desk")
	state.advance(3)
	assert(state.consume_tiny_interaction() == "front_desk")
	var id := str(state.repair_shop.jobs[0].id)
	state.accept_tiny_service(id)
	state.advance(8)
	scene._update_entities()
	await capture("courier")
	state.advance(15)
	state.collect_tiny_materials(id, [])
	state.advance(3)
	state.start_tiny_repair(id)
	state.advance(3)
	scene._show_repair_bench()
	scene._update_entities()
	await capture("diagnosis")
	state.advance(8)
	state.start_tiny_repair_method(id,"component_repair")
	state.advance(25)
	state.collect_tiny_device(id)
	state.advance(1)
	state.deliver_tiny_repair(id)
	state.advance(2)
	scene._show_outbound()
	scene._update_entities()
	await capture("pickup")
	root.size = Vector2i(1280,720)
	scene._update_entities()
	scene._show_parts_storage()
	await capture("small_storage")
	state.advance(20)
	assert(state.repair_shop.get_job(id).rewards_granted)
	scene.queue_free()
	print("Rendered repair walkthrough passed")
	quit(0)
